# Generated by Django 5.2.1 on 2025-08-05 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_completedcontent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='content',
            options={'ordering': ['order']},
        ),
    ]
